-- Insert 10 random agents with dummy data
INSERT INTO agents (
    id,
    organization_id,
    name,
    created_at,
    updated_at,
    greeting,
    personality,
    first_message,
    first_message_mode,
    hipaa_enabled,
    voice_config,
    model_config,
    transcriber_config,
    call_config,
    voicemail_config,
    analysis_config,
    artifact_config,
    message_config,
    speaking_config,
    monitor_config,
    server_config,
    metadata,
    credential_ids
) VALUES
    (
        'agent_1',
        'org_1',
        'Customer Service Bot',
        NOW(),
        NOW(),
        'Hello! How can I assist you today?',
        'Friendly and professional customer service representative',
        'Welcome to our service! How may I help you?',
        'immediate',
        false,
        '{
            "provider": "11labs",
            "voiceId": "rachel",
            "language": "en-US",
            "stability": 0.5,
            "similarityBoost": 0.7,
            "style": 0,
            "useSpeakerBoost": true,
            "optimizeStreamingLatency": 1,
            "enableSsmlParsing": true,
            "fallbackPlan": {
                "voices": [{"provider": "rime-ai", "voiceId": "allison"}]
            }
        }'::jsonb,
        '{
            "provider": "openai",
            "emotionRecognitionEnabled": true,
            "fallbackModels": ["gpt-4", "gpt-3.5-turbo"],
            "maxTokens": 150,
            "temperature": 0.7,
            "semanticCachingEnabled": true,
            "numFastTurns": 3
        }'::jsonb,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        '{"tags": ["customer-service", "general-support"]}'::jsonb,
        ARRAY['cred_1']
    ),
    (
        'agent_2',
        'org_1',
        'Sales Assistant',
        NOW(),
        NOW(),
        'Hi there! Looking for great deals?',
        'Enthusiastic and knowledgeable sales professional',
        'Let me show you our latest offers!',
        'immediate',
        false,
        '{
            "provider": "11labs",
            "voiceId": "josh",
            "language": "en-US",
            "stability": 0.6,
            "similarityBoost": 0.8,
            "style": 1,
            "useSpeakerBoost": true,
            "optimizeStreamingLatency": 1,
            "enableSsmlParsing": true,
            "fallbackPlan": {
                "voices": [{"provider": "rime-ai", "voiceId": "james"}]
            }
        }'::jsonb,
        '{
            "provider": "openai",
            "emotionRecognitionEnabled": true,
            "fallbackModels": ["gpt-4", "gpt-3.5-turbo"],
            "maxTokens": 200,
            "temperature": 0.8,
            "semanticCachingEnabled": true,
            "numFastTurns": 4
        }'::jsonb,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        '{"tags": ["sales", "product-specialist"]}'::jsonb,
        ARRAY['cred_2']
    ),
    (
        'agent_3',
        'org_1',
        'Technical Support',
        NOW(),
        NOW(),
        'Welcome to tech support! How can I assist?',
        'Patient and detail-oriented technical expert',
        'I can help you resolve any technical issues.',
        'immediate',
        false,
        '{
            "provider": "11labs",
            "voiceId": "emily",
            "language": "en-US",
            "stability": 0.8,
            "similarityBoost": 0.6,
            "style": 0,
            "useSpeakerBoost": true,
            "optimizeStreamingLatency": 1,
            "enableSsmlParsing": true,
            "fallbackPlan": {
                "voices": [{"provider": "rime-ai", "voiceId": "sarah"}]
            }
        }'::jsonb,
        '{
            "provider": "openai",
            "emotionRecognitionEnabled": false,
            "fallbackModels": ["gpt-4", "gpt-3.5-turbo"],
            "maxTokens": 300,
            "temperature": 0.5,
            "semanticCachingEnabled": true,
            "numFastTurns": 5
        }'::jsonb,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        '{"tags": ["technical-support", "troubleshooting"]}'::jsonb,
        ARRAY['cred_3']
    ),
    (
        'agent_4',
        'org_1',
        'Healthcare Assistant',
        NOW(),
        NOW(),
        'Hello! I'm here to assist with your healthcare needs.',
        'Compassionate and knowledgeable healthcare professional',
        'How can I help you with your health concerns today?',
        'immediate',
        true,
        '{
            "provider": "11labs",
            "voiceId": "sarah",
            "language": "en-US",
            "stability": 0.7,
            "similarityBoost": 0.7,
            "style": 0,
            "useSpeakerBoost": true,
            "optimizeStreamingLatency": 1,
            "enableSsmlParsing": true,
            "fallbackPlan": {
                "voices": [{"provider": "rime-ai", "voiceId": "emily"}]
            }
        }'::jsonb,
        '{
            "provider": "openai",
            "emotionRecognitionEnabled": true,
            "fallbackModels": ["gpt-4", "gpt-3.5-turbo"],
            "maxTokens": 250,
            "temperature": 0.6,
            "semanticCachingEnabled": true,
            "numFastTurns": 3
        }'::jsonb,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        '{"tags": ["healthcare", "medical-support"]}'::jsonb,
        ARRAY['cred_4']
    ),
    (
        'agent_5',
        'org_1',
        'Travel Advisor',
        NOW(),
        NOW(),
        'Hi! Ready to plan your next adventure?',
        'Enthusiastic and well-traveled advisor',
        'Let's find the perfect destination for you!',
        'immediate',
        false,
        '{
            "provider": "11labs",
            "voiceId": "michael",
            "language": "en-US",
            "stability": 0.6,
            "similarityBoost": 0.8,
            "style": 1,
            "useSpeakerBoost": true,
            "optimizeStreamingLatency": 1,
            "enableSsmlParsing": true,
            "fallbackPlan": {
                "voices": [{"provider": "rime-ai", "voiceId": "david"}]
            }
        }'::jsonb,
        '{
            "provider": "openai",
            "emotionRecognitionEnabled": true,
            "fallbackModels": ["gpt-4", "gpt-3.5-turbo"],
            "maxTokens": 200,
            "temperature": 0.8,
            "semanticCachingEnabled": true,
            "numFastTurns": 4
        }'::jsonb,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        '{"tags": ["travel", "vacation-planning"]}'::jsonb,
        ARRAY['cred_5']
    ),
    (
        'agent_6',
        'org_1',
        'Restaurant Concierge',
        NOW(),
        NOW(),
        'Welcome! Looking for a dining recommendation?',
        'Knowledgeable foodie and restaurant expert',
        'I can help you find the perfect dining spot!',
        'immediate',
        false,
        '{
            "provider": "11labs",
            "voiceId": "sophia",
            "language": "en-US",
            "stability": 0.7,
            "similarityBoost": 0.7,
            "style": 0,
            "useSpeakerBoost": true,
            "optimizeStreamingLatency": 1,
            "enableSsmlParsing": true,
            "fallbackPlan": {
                "voices": [{"provider": "rime-ai", "voiceId": "lisa"}]
            }
        }'::jsonb,
        '{
            "provider": "openai",
            "emotionRecognitionEnabled": true,
            "fallbackModels": ["gpt-4", "gpt-3.5-turbo"],
            "maxTokens": 180,
            "temperature": 0.7,
            "semanticCachingEnabled": true,
            "numFastTurns": 3
        }'::jsonb,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        '{"tags": ["dining", "restaurant-recommendations"]}'::jsonb,
        ARRAY['cred_6']
    ),
    (
        'agent_7',
        'org_1',
        'Fitness Coach',
        NOW(),
        NOW(),
        'Hey there! Ready to crush your fitness goals?',
        'Motivating and experienced fitness professional',
        'Let's create a workout plan that works for you!',
        'immediate',
        false,
        '{
            "provider": "11labs",
            "voiceId": "chris",
            "language": "en-US",
            "stability": 0.8,
            "similarityBoost": 0.8,
            "style": 1,
            "useSpeakerBoost": true,
            "optimizeStreamingLatency": 1,
            "enableSsmlParsing": true,
            "fallbackPlan": {
                "voices": [{"provider": "rime-ai", "voiceId": "mike"}]
            }
        }'::jsonb,
        '{
            "provider": "openai",
            "emotionRecognitionEnabled": true,
            "fallbackModels": ["gpt-4", "gpt-3.5-turbo"],
            "maxTokens": 220,
            "temperature": 0.7,
            "semanticCachingEnabled": true,
            "numFastTurns": 4
        }'::jsonb,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        '{"tags": ["fitness", "health-coaching"]}'::jsonb,
        ARRAY['cred_7']
    ),
    (
        'agent_8',
        'org_1',
        'Real Estate Agent',
        NOW(),
        NOW(),
        'Hello! Looking for your dream home?',
        'Professional and knowledgeable real estate expert',
        'I can help you find the perfect property!',
        'immediate',
        false,
        '{
            "provider": "11labs",
            "voiceId": "alex",
            "language": "en-US",
            "stability": 0.7,
            "similarityBoost": 0.7,
            "style": 0,
            "useSpeakerBoost": true,
            "optimizeStreamingLatency": 1,
            "enableSsmlParsing": true,
            "fallbackPlan": {
                "voices": [{"provider": "rime-ai", "voiceId": "robert"}]
            }
        }'::jsonb,
        '{
            "provider": "openai",
            "emotionRecognitionEnabled": true,
            "fallbackModels": ["gpt-4", "gpt-3.5-turbo"],
            "maxTokens": 250,
            "temperature": 0.6,
            "semanticCachingEnabled": true,
            "numFastTurns": 3
        }'::jsonb,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        '{"tags": ["real-estate", "property-search"]}'::jsonb,
        ARRAY['cred_8']
    ),
    (
        'agent_9',
        'org_1',
        'Financial Advisor',
        NOW(),
        NOW(),
        'Welcome! Need help with financial planning?',
        'Trustworthy and experienced financial professional',
        'Let's discuss your financial goals and create a plan.',
        'immediate',
        false,
        '{
            "provider": "11labs",
            "voiceId": "james",
            "language": "en-US",
            "stability": 0.8,
            "similarityBoost": 0.6,
            "style": 0,
            "useSpeakerBoost": true,
            "optimizeStreamingLatency": 1,
            "enableSsmlParsing": true,
            "fallbackPlan": {
                "voices": [{"provider": "rime-ai", "voiceId": "william"}]
            }
        }'::jsonb,
        '{
            "provider": "openai",
            "emotionRecognitionEnabled": false,
            "fallbackModels": ["gpt-4", "gpt-3.5-turbo"],
            "maxTokens": 300,
            "temperature": 0.5,
            "semanticCachingEnabled": true,
            "numFastTurns": 3
        }'::jsonb,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        '{"tags": ["finance", "investment-advice"]}'::jsonb,
        ARRAY['cred_9']
    ),
    (
        'agent_10',
        'org_1',
        'Language Tutor',
        NOW(),
        NOW(),
        '¡Hola! Ready to practice your language skills?',
        'Patient and encouraging language instructor',
        'Let's start improving your language abilities!',
        'immediate',
        false,
        '{
            "provider": "11labs",
            "voiceId": "maria",
            "language": "es-ES",
            "stability": 0.7,
            "similarityBoost": 0.7,
            "style": 0,
            "useSpeakerBoost": true,
            "optimizeStreamingLatency": 1,
            "enableSsmlParsing": true,
            "fallbackPlan": {
                "voices": [{"provider": "rime-ai", "voiceId": "ana"}]
            }
        }'::jsonb,
        '{
            "provider": "openai",
            "emotionRecognitionEnabled": true,
            "fallbackModels": ["gpt-4", "gpt-3.5-turbo"],
            "maxTokens": 200,
            "temperature": 0.7,
            "semanticCachingEnabled": true,
            "numFastTurns": 4
        }'::jsonb,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        DEFAULT,
        '{"tags": ["education", "language-learning"]}'::jsonb,
        ARRAY['cred_10']
    );
